name: Node.js CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3

    # Server
    - name: Setup Node.js for Server
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: server/package-lock.json
    - name: Install server dependencies
      working-directory: ./server
      run: npm install
    - name: Build server
      working-directory: ./server
      run: npm run build --if-present

    # Client
    - name: Setup Node.js for Client
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: client/package-lock.json
    - name: Install client dependencies
      working-directory: ./client
      run: npm install
    - name: Build client
      working-directory: ./client
      run: npm run build --if-present
    - name: Test client
      working-directory: ./client
      run: npm test
